[tool.poetry]
name = "pypat"
version = "0.1.1"
description = ""
authors = ["Pix-00 <15878537+Pix-00@users.noreply.github.com>"]
license = "Apache-2.0"

[tool.poetry.dependencies]
python = "^3.8"
cryptography = "^2.9.2"

[tool.poetry.dev-dependencies]
isort = {extras = ["pyproject"], version = "^4.3.21"}
yapf = "^0.30.0"
pre-commit = "^2.4.0"

[tool.isort]
line_length = 100
known_third_party = ["cryptography"]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
