[tool.poetry]
name = "json_api"
version = "0.1.0"
description = ""
authors = ["Pix-00 <15878537+Pix-00@users.noreply.github.com>"]
license = "Apache-2.0"

[tool.poetry.dependencies]
python = "^3.8"
jsonschema = "^3.2.0"

[tool.poetry.dev-dependencies]
isort = {extras = ["pyproject"], version = "^4.3.21"}
yapf = "^0.30.0"
pylint = "^2.5.3"
mypy = "^0.780"
pre-commit = "^2.5.1"

[tool.isort]
force_to_top = "false"
line_length = 100
known_third_party = ["IP2Location", "alembic", "bs4", "cryptography", "flask", "flask_json", "flask_jsonform", "flask_redis", "flask_sqlalchemy", "ip2loc", "jsonform", "mailgun", "msal", "onedrive", "passlib", "pypat", "requests", "sentry_sdk", "singleton", "sqlalchemy", "sqlalchemy_", "toml", "werkzeug"]

[tool.pylint.messages_control]
disable = """,
    invalid-name,
    import-outside-toplevel,
    missing-module-docstring,
    missing-class-docstring,
    missing-function-docstring,

    """

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
